# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_completed',
        ),
        migrations.AddField(
            model_name='project',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 5, 13, 11, 20, 56, 930093)),
            preserve_default=False,
        ),
    ]
