# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160513_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='splash',
            field=models.ImageField(blank=True, upload_to='splash/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
