# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160513_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['date_uploaded']},
        ),
    ]
