# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160513_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme', models.TextField()),
                ('profilepic', models.ImageField(upload_to='profilepic/')),
            ],
        ),
    ]
