# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-11 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
    ]
