# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-12 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_emails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
