# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_auto_20170412_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails_list', models.ManyToManyField(to='subscribe.Emails')),
            ],
        ),
    ]
