# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-12 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_emailslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailslist',
            name='emails_list',
        ),
        migrations.DeleteModel(
            name='EmailsList',
        ),
    ]
