language: python
python:
  - "2.7"
  - "3.5"
install: "pip install -r requirements.txt"
# script: python portfolio/manage.py test blog/tests/
script: python portfolio/manage.py test portfolio/projects/
