# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-16 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161215_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='vidsos',
            field=models.ManyToManyField(to='blog.BlogVideo'),
        ),
    ]
