# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-17 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_vidsos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='vidsos',
            new_name='videos',
        ),
    ]
