# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-18 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161217_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='images',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='videos',
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.DeleteModel(
            name='BlogVideo',
        ),
    ]
