# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-18 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161218_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_uploaded']},
        ),
    ]
