# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-18 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161218_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
